#!/usr/bin/env node

'use strict'
var c = require ("skilstak-colors")

function print(message) {
  process.stdout.write(message + "\n");
}

print(c.clear + c.multi("Welcome to the Magic Eightball!"));

